from core import engineering as E

def F(key, fr, ar, en, ion=None):
    d = {"key": key, "label": {"fr": fr, "ar": ar, "en": en}}
    if ion:
        d["ion"] = ion
    return d

def _wc(v):
    cat = {"Ca": (v["ca"], 20.04), "Mg": (v["mg"], 12.15),
           "Na": (v["na"], 23.0), "K": (v["k"], 39.1)}
    an = {"HCO3": (v["hco3"], 61.0), "Cl": (v["cl"], 35.45), "SO4": (v["so4"], 48.03)}
    return E.water_chemistry(cat, an, v["sio2"], v["ca"], v["mg"], v["ph"],
                             v["tds"], v["temp"], v["alk"], v["pca"], v["palk"], v["ksd"])

MODULES = [
 {"id": "water", "title": {"fr": "Chimie de l'eau & équilibre ionique",
                           "ar": "كيمياء المياه والاتزان الأيوني",
                           "en": "Water Chemistry & Ionic Balance"},
  "fields": [F("ca", "Ca²⁺", "الكالسيوم", "Calcium", "Ca"),
             F("mg", "Mg²⁺", "المغنيسيوم", "Magnesium", "Mg"),
             F("na", "Na⁺", "الصوديوم", "Sodium", "Na"),
             F("k", "K⁺", "البوتاسيوم", "Potassium", "K"),
             F("hco3", "HCO₃⁻", "البيكربونات", "Bicarbonate", "HCO3"),
             F("cl", "Cl⁻", "الكلوريد", "Chloride", "Cl"),
             F("so4", "SO₄²⁻", "الكبريتات", "Sulfate", "SO4"),
             F("sio2", "SiO₂ (mg/L)", "السيليكا", "Silica"),
             F("ph", "pH", "pH", "pH"),
             F("tds", "TDS (mg/L)", "الأملاح الذائبة", "TDS"),
             F("temp", "Température (°C)", "الحرارة", "Temperature"),
             F("alk", "Alcalinité (mg/L CaCO₃)", "القلوية", "Alkalinity"),
             F("pca", "pCa", "pCa", "pCa"),
             F("palk", "pAlk", "pAlk", "pAlk"),
             F("ksd", "K (Stiff&Davis)", "ثابت K", "K constant")],
  "compute": _wc},

 {"id": "sat", "title": {"fr": "Saturation minérale (%)", "ar": "تشبع المعادن", "en": "Mineral Saturation"},
  "fields": [F("ca", "Ca (mg/L)", "الكالسيوم", "Ca"),
             F("so4", "SO₄ (mg/L)", "الكبريتات", "SO4"),
             F("ba", "Ba (mg/L)", "الباريوم", "Ba"),
             F("sr", "Sr (mg/L)", "السترونشيوم", "Sr"),
             F("fl", "F (mg/L)", "الفلوريد", "F"),
             F("sio2", "SiO₂ (mg/L)", "السيليكا", "SiO2"),
             F("k1", "Ksp CaSO₄", "Ksp CaSO4", "Ksp CaSO4"),
             F("k2", "Ksp BaSO₄", "Ksp BaSO4", "Ksp BaSO4"),
             F("k3", "Ksp SrSO₄", "Ksp SrSO4", "Ksp SrSO4"),
             F("k4", "Ksp CaF₂", "Ksp CaF2", "Ksp CaF2"),
             F("ss", "Solubilité SiO₂ (mg/L)", "ذوبانية السيليكا", "SiO2 solubility")],
  "compute": lambda v: E.mineral_saturation(v["ca"], v["so4"], v["ba"], v["sr"],
          v["fl"], v["sio2"], v["k1"], v["k2"], v["k3"], v["k4"], v["ss"])},

 {"id": "uf", "title": {"fr": "Ultrafiltration (UF)", "ar": "الترشيح الفائق", "en": "Ultrafiltration"},
  "fields": [F("q", "Débit filtrat (L/h)", "تدفق الراشح", "Filtrate flow"),
             F("a", "Surface (m²)", "المساحة", "Area"),
             F("pf", "P alimentation (bar)", "ضغط التغذية", "Feed P"),
             F("pc", "P concentrat (bar)", "ضغط المركز", "Concentrate P"),
             F("pfi", "P filtrat (bar)", "ضغط الراشح", "Filtrate P"),
             F("vf", "Volume filtrat", "حجم الراشح", "Filtrate vol."),
             F("vbw", "Volume backwash", "حجم الغسيل العكسي", "Backwash vol."),
             F("tcf", "TCF", "معامل الحرارة", "TCF")],
  "compute": lambda v: E.uf(v["q"], v["a"], v["pf"], v["pc"], v["pfi"],
                            v["vf"], v["vbw"], v["tcf"])},

 {"id": "ro", "title": {"fr": "Osmose inverse / Nanofiltration", "ar": "التناضح العكسي/النانوي", "en": "RO / NF"},
  "fields": [F("qp", "Q perméat (m³/h)", "تدفق النفاذ", "Permeate flow"),
             F("qf", "Q alimentation (m³/h)", "تدفق التغذية", "Feed flow"),
             F("cp", "C perméat (mg/L)", "تركيز النفاذ", "Permeate conc."),
             F("cf", "C alimentation (mg/L)", "تركيز التغذية", "Feed conc."),
             F("pf", "P alimentation (bar)", "ضغط التغذية", "Feed P"),
             F("dp", "ΔP étage (bar)", "فقد الضغط بالمرحلة", "Stage ΔP"),
             F("pp", "P perméat (bar)", "ضغط النفاذ", "Permeate P"),
             F("oa", "Osmotique moy. (bar)", "الأسموزي الوسطي", "Avg osmotic"),
             F("op", "Osmotique perméat (bar)", "الأسموزي للنفاذ", "Permeate osmotic"),
             F("A", "Constante A", "ثابت A", "A constant"),
             F("B", "Constante B", "ثابت B", "B constant"),
             F("cm", "C membrane (mg/L)", "تركيز الغشاء", "Membrane conc."),
             F("km", "k transfert", "معامل النقل k", "k mass transfer"),
             F("y", "Y récupération (0-1)", "الاسترجاع Y", "Recovery Y"),
             F("qa", "Q perm. actuel", "النفاذ الفعلي", "Actual Q perm"),
             F("ni", "NDP initial", "NDP الابتدائي", "Initial NDP"),
             F("na", "NDP actuel", "NDP الفعلي", "Actual NDP"),
             F("ti", "TCF initial", "TCF الابتدائي", "Initial TCF"),
             F("ta", "TCF actuel", "TCF الفعلي", "Actual TCF")],
  "compute": lambda v: E.ro_nf(v["qp"], v["qf"], v["cp"], v["cf"], v["pf"], v["dp"],
          v["pp"], v["oa"], v["op"], v["A"], v["B"], v["cm"], v["km"], v["y"],
          v["qa"], v["ni"], v["na"], v["ti"], v["ta"])},

 {"id": "ix", "title": {"fr": "Échange d'ions (IX)", "ar": "التبادل الأيوني", "en": "Ion Exchange"},
  "fields": [F("vw", "Volume eau (m³)", "حجم الماء", "Water volume"),
             F("vr", "Volume résine (L)", "حجم الراتنج", "Resin volume"),
             F("eq", "Équivalents éliminés (eq)", "المكافئات المزالة", "Eq removed"),
             F("mc", "Masse chimique (g)", "كتلة المادة", "Chemical mass"),
             F("deq", "Dosage appliqué (eq/L)", "الجرعة المطبقة", "Applied dosage")],
  "compute": lambda v: E.ion_exchange(v["vw"], v["vr"], v["eq"], v["mc"], v["deq"])},

 {"id": "blend", "title": {"fr": "Mélange & SEC", "ar": "الخلط واستهلاك الطاقة", "en": "Blending & SEC"},
  "fields": [F("q1", "Q1 (m³/h)", "التدفق 1", "Flow 1"),
             F("c1", "C1 (mg/L)", "التركيز 1", "Conc 1"),
             F("q2", "Q2 (m³/h)", "التدفق 2", "Flow 2"),
             F("c2", "C2 (mg/L)", "التركيز 2", "Conc 2"),
             F("p", "Puissance (kW)", "القدرة", "Power"),
             F("qp", "Débit produit (m³/h)", "تدفق المنتج", "Product flow")],
  "compute": lambda v: {**E.blending(v["q1"], v["c1"], v["q2"], v["c2"]),
                        **E.sec(v["p"], v["qp"])}},

 {"id": "dose", "title": {"fr": "Dosage chimique", "ar": "الجرعات الكيميائية", "en": "Chemical Dosing"},
  "fields": [F("q", "Débit eau (m³/h)", "تدفق الماء", "Water flow"),
             F("d", "Dose (mg/L)", "الجرعة", "Dose"),
             F("c", "Concentration (%)", "التركيز %", "Concentration"),
             F("sg", "Densité relative", "الكثافة النسبية", "Spec. gravity"),
             F("al", "Dose alun (mg/L)", "جرعة الشبة", "Alum dose"),
             F("cl", "Chlore résiduel (mg/L)", "الكلور المتبقي", "Cl residual"),
             F("ct", "Temps contact (min)", "زمن التماس", "Contact time")],
  "compute": lambda v: E.chemical_dosing(v["q"], v["d"], v["c"], v["sg"],
                                         v["al"], v["cl"], v["ct"])},

 {"id": "media", "title": {"fr": "Filtration sur média", "ar": "الترشيح بالرمل", "en": "Media Filtration"},
  "fields": [F("q", "Débit (m³/h)", "التدفق", "Flow"),
             F("af", "Surface filtre (m²)", "مساحة المرشح", "Filter area"),
             F("hs", "H lit repos (m)", "ارتفاع المستقر", "Settled bed"),
             F("he", "H lit expansé (m)", "ارتفاع المتمدد", "Expanded bed"),
             F("as", "Surface décanteur (m²)", "مساحة المرسّب", "Settling area")],
  "compute": lambda v: E.media_filtration(v["q"], v["af"], v["hs"], v["he"], v["as"])},

 {"id": "bio", "title": {"fr": "Traitement biologique", "ar": "المعالجة البيولوجية", "en": "Biological Wastewater"},
  "fields": [F("q", "Débit (m³/h)", "التدفق", "Flow"),
             F("bod", "BOD5 (mg/L)", "BOD5", "BOD5"),
             F("va", "Volume aération (m³)", "حجم التهوية", "Aeration vol."),
             F("mlvss", "MLVSS (mg/L)", "MLVSS", "MLVSS"),
             F("mlss", "MLSS (mg/L)", "MLSS", "MLSS"),
             F("ssv", "Vase 30 min (mL/L)", "الحمأة المترسبة", "Settled sludge"),
             F("qw", "Q purge (m³/j)", "تدفق التصريف", "Waste flow"),
             F("xw", "X purge (mg/L)", "تركيز التصريف", "Waste conc."),
             F("qe", "Q effluent (m³/j)", "تدفق المخرج", "Effluent flow"),
             F("xe", "X effluent (mg/L)", "تركيز المخرج", "Effluent conc."),
             F("vt", "Volume bassin (m³)", "حجم الخزان", "Tank volume")],
  "compute": lambda v: E.wastewater(v["q"], v["bod"], v["va"], v["mlvss"], v["mlss"],
          v["ssv"], v["qw"], v["xw"], v["qe"], v["xe"], v["vt"])},

 {"id": "pump", "title": {"fr": "Hydraulique des pompes", "ar": "هيدروليكا المضخات", "en": "Pump Hydraulics"},
  "fields": [F("q", "Débit (m³/h)", "التدفق", "Flow"),
             F("hds", "H refoulement stat. (m)", "شحنة الطرد الساكنة", "Discharge static"),
             F("hss", "H aspiration stat. (m)", "شحنة السحب الساكنة", "Suction static"),
             F("hf", "Perte frottement (m)", "فقد الاحتكاك", "Friction loss"),
             F("hm", "Pertes mineures (m)", "الفقد الثانوي", "Minor losses"),
             F("pd", "P refoulement (bar)", "ضغط الطرد", "Discharge P"),
             F("ps", "P aspiration (bar)", "ضغط السحب", "Suction P"),
             F("sg", "Densité relative", "الكثافة النسبية", "Spec. gravity"),
             F("ep", "Rend. pompe (0-1)", "كفاءة المضخة", "Pump eff."),
             F("em", "Rend. moteur (0-1)", "كفاءة المحرك", "Motor eff."),
             F("ev", "Rend. VFD (0-1)", "كفاءة VFD", "VFD eff."),
             F("f", "Facteur frottement f", "معامل الاحتكاك", "Friction factor"),
             F("L", "Longueur tuyau (m)", "طول الأنبوب", "Pipe length"),
             F("D", "Diamètre (m)", "القطر", "Diameter"),
             F("vel", "Vitesse (m/s)", "السرعة", "Velocity"),
             F("hb", "H barométrique (m)", "الشحنة البارومترية", "Barometric H"),
             F("hsf", "Perte aspiration (m)", "فقد السحب", "Suction friction"),
             F("hv", "H vapeur (m)", "ضغط البخار", "Vapor head")],
  "compute": lambda v: E.pump_hydraulics(v["q"], v["hds"], v["hss"], v["hf"], v["hm"],
          v["pd"], v["ps"], v["sg"], v["ep"], v["em"], v["ev"], v["f"],
          v["L"], v["D"], v["vel"], v["hb"], v["hsf"], v["hv"])},

 {"id": "ropump", "title": {"fr": "Pompes HP & récupération d'énergie", "ar": "مضخات الضغط العالي وERD", "en": "RO HP Pumps & ERD"},
  "fields": [F("ndp", "NDP (bar)", "NDP", "NDP"),
             F("oa", "Osmotique moy. (bar)", "الأسموزي الوسطي", "Avg osmotic"),
             F("dp", "ΔP étages (bar)", "فقد المراحل", "Stages ΔP"),
             F("pb", "Contre-pression perméat (bar)", "ضغط النفاذ العكسي", "Permeate back-P"),
             F("qf", "Q alimentation (m³/h)", "تدفق التغذية", "Feed flow"),
             F("qp", "Q perméat (m³/h)", "تدفق النفاذ", "Permeate flow"),
             F("qc", "Q concentrat (m³/h)", "تدفق المركز", "Concentrate flow"),
             F("pc", "P concentrat (bar)", "ضغط المركز", "Concentrate P"),
             F("erd", "Rend. ERD (0-1)", "كفاءة ERD", "ERD eff."),
             F("ep", "Rend. pompe (0-1)", "كفاءة المضخة", "Pump eff."),
             F("em", "Rend. moteur (0-1)", "كفاءة المحرك", "Motor eff.")],
  "compute": lambda v: E.ro_pumps(v["ndp"], v["oa"], v["dp"], v["pb"], v["qf"],
          v["qp"], v["qc"], v["pc"], v["erd"], v["ep"], v["em"])},

 {"id": "dosepump", "title": {"fr": "Pompes doseuses", "ar": "مضخات الجرعات", "en": "Dosing Pumps"},
  "fields": [F("q", "Débit eau brute (m³/h)", "تدفق الماء الخام", "Raw water flow"),
             F("d", "Dose cible (mg/L)", "الجرعة المستهدفة", "Target dose"),
             F("c", "Concentration (%)", "التركيز %", "Concentration"),
             F("sg", "Densité relative", "الكثافة النسبية", "Spec. gravity"),
             F("qm", "Q max nominale (L/h)", "التدفق الأقصى", "Max rated Q"),
             F("st", "Course (%)", "الشوط %", "Stroke %"),
             F("fr", "Fréquence (%)", "التردد %", "Frequency %"),
             F("vm", "Volume tiré (mL)", "الحجم المسحوب", "Volume drawn"),
             F("ts", "Temps (s)", "الزمن (ث)", "Time (s)"),
             F("pl", "P ligne max (bar)", "ضغط الخط الأقصى", "Max line P"),
             F("dv", "ΔP vanne injection (bar)", "فقد صمام الحقن", "Valve ΔP")],
  "compute": lambda v: E.dosing_pumps(v["q"], v["d"], v["c"], v["sg"], v["qm"],
          v["st"], v["fr"], v["vm"], v["ts"], v["pl"], v["dv"])},

 {"id": "inst", "title": {"fr": "Instrumentation (4-20 mA)", "ar": "الأتمتة والتحويل", "en": "Instrumentation"},
  "fields": [F("i", "Courant (mA)", "التيار", "Current"),
             F("pmin", "PV min", "الحد الأدنى", "PV min"),
             F("pmax", "PV max", "الحد الأقصى", "PV max"),
             F("cond", "Conductivité (µS/cm)", "التوصيلية", "Conductivity"),
             F("k", "Facteur k (0.55-0.70)", "المعامل k", "k factor")],
  "compute": lambda v: E.instrumentation(v["i"], v["pmin"], v["pmax"], v["cond"], v["k"])},

 {"id": "aff", "title": {"fr": "Lois d'affinité", "ar": "قوانين التناظر", "en": "Affinity Laws"},
  "fields": [F("q1", "Q1 (m³/h)", "التدفق 1", "Flow 1"),
             F("h1", "H1 (m)", "الشحنة 1", "Head 1"),
             F("p1", "P1 (kW)", "القدرة 1", "Power 1"),
             F("n1", "N1 (tr/min)", "السرعة 1", "Speed 1"),
             F("n2", "N2 (tr/min)", "السرعة 2", "Speed 2"),
             F("d1", "D1 (mm)", "القطر 1", "Diameter 1"),
             F("d2", "D2 (mm)", "القطر 2", "Diameter 2")],
  "compute": lambda v: E.affinity(v["q1"], v["h1"], v["p1"], v["n1"],
                                  v["n2"], v["d1"], v["d2"])},
]
